### ISSUE TITLE
Markdown Links aren't rendered or created properly

### ISSUE THREAD

**Issue by aidanlw505** [RyotaUshio/obsidian-math-booster#175]
The first pair of links are ones I created by typing `[[`. One with the "Use [[WikiLinks]]" option disabled to use markdown links. The second pair are links created by typing `\eqref`, again with one created while not using wikilinks. 

![image](https://github.com/RyotaUshio/obsidian-math-booster/assets/65873709/4e7bd279-dfe3-4e5a-ae42-d7677b59d0b0)

![image](https://github.com/RyotaUshio/obsidian-math-booster/assets/65873709/7bc1f3db-0d4a-43bf-bbd6-bb9c41b96978)

The first problem is that `[](#^881de2)` doesn't get rendered with equation number. The second issue is that  when creating a reference using `\eqref`, the filename is added as linktext.

**Comment by RyotaUshio** [comment]
A currently available workaround for this problem is to put `#^blockID` in the `[ ]`, as shown in the image below.

<img width="735" alt="image" src="https://github.com/RyotaUshio/obsidian-math-booster/assets/72342591/74ef5ece-9a2d-4185-bbae-58aec31e7981">

I know it's not a clean solution, but this way you can display equation numbers even when using markdown links.

<img width="723" alt="image" src="https://github.com/RyotaUshio/obsidian-math-booster/assets/72342591/9de3cbca-fdf8-41b6-a26e-ae307e5433ef">

**Comment by RyotaUshio** [comment]
Update: From the next release on, `\ref` & `\eqref` will insert wikilinks regardless of the user's `Use [[Wikilinks]]` setting.
Please use this auto-completion for theorems or equations if you want to keep using markdown links for other links.

It would be great if this plugin (and MathLinks) could support markdown links, but they are not suitable in this case because they are bad (or terrible) at dynamic updates.
