### ISSUE TITLE
In 2.0.0-alpha2, some callouts seem to not be fully recognized by the plugin 

### ISSUE THREAD

**Issue by joelatschool** [RyotaUshio/obsidian-math-booster#191]
I'm trying out 2.0.0-alpha2, and I've noticed that in some notes, for reasons that I don't quite understand, certain callouts seem to be picked up by the plugin (and thus numbered, etc) in live-preview mode but not in reading mode. These callouts will appear strangely in reading mode, sometimes displaying without a number or even without any title at all. Further, when these callouts are later referenced, the reference will appear like a normal block link. I have attached a file from my vault that displays this issue:

[Integrity over Commutative Rings.md](https://github.com/RyotaUshio/obsidian-math-booster/files/13401158/Integrity.over.Commutative.Rings.md)

(Other than that though I've been very happy so far with 2.0.0 :) )

**Comment by RyotaUshio** [comment]
First of all, thank you a lot for trying the alpha and giving me detailed feedback!!

A good news is that this problem has already been fixed in https://github.com/RyotaUshio/obsidian-math-booster/commit/b97b5b2464b8f56f13ba705587e7721cc8a3e82f!

> Fixed theorem callout without title not recognized as theorem callout by the parser & fixed theorem callout without title is recoginized as having one if abbreviation/alias (like thm,lem,cor,...) was used

The current latest release is `2.0.0-beta` and you can now install it via BRAT.

A bad new is, though, while reading view has almost no problem now, live preview has some auto-numbering issues.
I will fix it before officially release 2.0.0. 

Thank you again for your report! Feel free to reopen it if the lastest version doesn't resolve the problem.
